In [91]:
import numpy as np
import pandas as pd

In [2]:
lst = [[1,2,3], [4,5,6], [7,8,9]]

In [4]:
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
(arr.shape, arr.size, arr.ndim, arr.dtype)

((3, 3), 9, 2, dtype('int32'))

In [36]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 11) #stop is exclusive

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.linspace(0, 10, 11) #last number defines the number of data points, both start and end points are inclusive

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [18]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [27]:
np.random.rand(2,3,4) #3 dimensional array

array([[[0.03473992, 0.94921148, 0.61947245, 0.66654067],
        [0.44007483, 0.56348353, 0.93515908, 0.20354301],
        [0.64552634, 0.44380293, 0.69358127, 0.66982484]],

       [[0.04857338, 0.59080307, 0.83589742, 0.63306422],
        [0.75288288, 0.84741665, 0.96452881, 0.82665535],
        [0.41128907, 0.75707738, 0.67685628, 0.70881231]]])

In [28]:
np.random.randint(low=2, high=6, size=(2,3)) #high is exclusive

array([[2, 4, 5],
       [2, 5, 5]])

In [50]:
a = np.random.randn(2,3,4) #random normal distribution where mean=0 and sd= 1 and abs(data.any_value) < 3*sd
a

array([[[-0.14587738, -0.05618252, -2.29966067,  1.44970367],
        [-0.9403928 , -0.32283912, -0.29181893,  1.57428831],
        [-0.09911635, -0.57231235,  0.60440027,  0.04102338]],

       [[ 1.08805899, -0.50954181, -0.41006637,  0.26364687],
        [-0.40860616, -1.74263924,  0.93491158,  0.01829209],
        [-0.49040865, -2.48385201, -0.37358262, -0.35591282]]])

In [57]:
a = a.reshape(6,4) # it just reshapes the view unless you assign it to the (new) variable
a

array([[-0.14587738, -0.05618252, -2.29966067,  1.44970367],
       [-0.9403928 , -0.32283912, -0.29181893,  1.57428831],
       [-0.09911635, -0.57231235,  0.60440027,  0.04102338],
       [ 1.08805899, -0.50954181, -0.41006637,  0.26364687],
       [-0.40860616, -1.74263924,  0.93491158,  0.01829209],
       [-0.49040865, -2.48385201, -0.37358262, -0.35591282]])

In [58]:
(a.min(), a.max(), a.argmin(), a.argmax()) #only the 1st occurance is returned in a flattened format

(-2.4838520074754045, 1.5742883144276691, 21, 7)

In [60]:
a.argmax(axis=0)

array([3, 0, 4, 1], dtype=int64)

In [62]:
m,n,p,q = (None,)*4
a[m:n,p:q]

array([[-0.14587738, -0.05618252, -2.29966067,  1.44970367],
       [-0.9403928 , -0.32283912, -0.29181893,  1.57428831],
       [-0.09911635, -0.57231235,  0.60440027,  0.04102338],
       [ 1.08805899, -0.50954181, -0.41006637,  0.26364687],
       [-0.40860616, -1.74263924,  0.93491158,  0.01829209],
       [-0.49040865, -2.48385201, -0.37358262, -0.35591282]])

In [ ]:
a[2:5,3:] #be careful that you need ':' to output a 2-D array

In [45]:
my_list = "1 2 3 4 5 6".split() #elements are of the string type. To convert you can either use map function or list comprehens.
str_arr = np.array(my_list)
str_arr

array(['1', '2', '3', '4', '5', '6'], dtype='<U1')

In [46]:
str_arr.astype(int)

array([1, 2, 3, 4, 5, 6])

In [47]:
str_arr.astype(float)

array([1., 2., 3., 4., 5., 6.])

broadcasting to a slice of an array changes the array as well because every slice is referred to the original array

In [130]:
d = np.arange(25).reshape(5,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [131]:
d_slice = d[2:, :]
d_slice[:,:] = 3.5
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [132]:
d_fl = d.astype(float)
d_slice = d_fl[2:, :] #this is called basic indexing which only creates a view of the original array
d_slice[:, :] = 3.5
d_fl

array([[0. , 1. , 2. , 3. , 4. ],
       [5. , 6. , 7. , 8. , 9. ],
       [3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5]])

# conditional selection

In [144]:
arr = np.arange(25).reshape(5,5).astype(float)
arr

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [145]:
arr>9

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [146]:
sub_arr = arr[arr>9] # note that the condition flatten the array! This is called advanced indexing
sub_arr

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24.])

In [147]:
(sub_arr.ndim, sub_arr.size, sub_arr.shape, sub_arr.dtype)

(1, 15, (15,), dtype('float64'))

In [148]:
sub_arr[:] = 14
arr

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [149]:
arr[arr>9] = 3.5
arr

array([[0. , 1. , 2. , 3. , 4. ],
       [5. , 6. , 7. , 8. , 9. ],
       [3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5]])

In [150]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])

In [151]:
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [160]:
x.shape

(2, 3, 1)

In [153]:
x[...,0]

array([[1, 2, 3],
       [4, 5, 6]])

In [159]:
x[:,:,0]

array([[1, 2, 3],
       [4, 5, 6]])

# operations

In [161]:
arr = np.arange(25).reshape(5,5).astype(float)
arr

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [162]:
arr * 2

array([[ 0.,  2.,  4.,  6.,  8.],
       [10., 12., 14., 16., 18.],
       [20., 22., 24., 26., 28.],
       [30., 32., 34., 36., 38.],
       [40., 42., 44., 46., 48.]])

In [163]:
arr + 2 * arr / 4

array([[ 0. ,  1.5,  3. ,  4.5,  6. ],
       [ 7.5,  9. , 10.5, 12. , 13.5],
       [15. , 16.5, 18. , 19.5, 21. ],
       [22.5, 24. , 25.5, 27. , 28.5],
       [30. , 31.5, 33. , 34.5, 36. ]])

In [170]:
def func(x):
    y = x+2*x/4
    return y

In [171]:
arr2 = func(arr)
arr2

array([[ 0. ,  1.5,  3. ,  4.5,  6. ],
       [ 7.5,  9. , 10.5, 12. , 13.5],
       [15. , 16.5, 18. , 19.5, 21. ],
       [22.5, 24. , 25.5, 27. , 28.5],
       [30. , 31.5, 33. , 34.5, 36. ]])

In [172]:
arr3 = np.zeros(arr.shape)
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [173]:
arr3 = np.zeros_like(arr)
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [175]:
arr

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [176]:
arr2

array([[ 0. ,  1.5,  3. ,  4.5,  6. ],
       [ 7.5,  9. , 10.5, 12. , 13.5],
       [15. , 16.5, 18. , 19.5, 21. ],
       [22.5, 24. , 25.5, 27. , 28.5],
       [30. , 31.5, 33. , 34.5, 36. ]])

In [174]:
arr3[arr2 > arr +10 ] = 13 #element-wise comparison for same shape arrays
arr3

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0., 13., 13., 13., 13.]])

In [187]:
xx = np.arange(25).reshape(5,5).astype(float)
np.multiply(arr, arr2, where=(arr2>arr+10), out=np.full_like(xx, fill_value=np.inf))

array([[  inf,   inf,   inf,   inf,   inf],
       [  inf,   inf,   inf,   inf,   inf],
       [  inf,   inf,   inf,   inf,   inf],
       [  inf,   inf,   inf,   inf,   inf],
       [  inf, 661.5, 726. , 793.5, 864. ]])

# Pandas

lets start with series

In [197]:
lst = [10,20,30]
arr = np.array(lst)
index = ["a", "b", "c"]

In [198]:
dic = {key:value for (key, value) in zip(index, lst)} #dictionary comprehension

In [199]:
dic

{'a': 10, 'b': 20, 'c': 30}

you can construct pd.Series from a list, array or a dictionary. if data=list or array then you can specify the index as another list or array

In [200]:
pd.Series(dic)

a    10
b    20
c    30
dtype: int64

In [203]:
pd.Series(data=lst, index=index)

a    10
b    20
c    30
dtype: int64

In [205]:
ser1 = pd.Series(data=arr, index=index) #Note the difference in dtype
ser1

a    10
b    20
c    30
dtype: int32

In [206]:
ser1['a']

10

Now let's move on to the data frames

pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False) this is a very flexible format. look at the help

In [207]:
pd.DataFrame(data={'col1': [1,2,3], 'col2': [4,5,6], 'col3': [7,8,9]}, index=['a','b', 'c'])

col1  col2  col3
a     1     4     7
b     2     5     8
c     3     6     9

In [215]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]]).T #Note that I have to transpose the array to get the same data frame
col = ['col1', 'col2', 'col3']
index=['a','b', 'c']
pd.DataFrame(data=arr, index=index, columns=col)

col1  col2  col3
a     1     4     7
b     2     5     8
c     3     6     9

In [220]:
pd.DataFrame(data={'col1': ser1, 'col2': ser1*2}) #if you want to construct it from series

col1  col2
a    10    20
b    20    40
c    30    60

In [224]:
df = pd.DataFrame(data={col:ser1 for col in "col1 col2 col3".split()})
df

col1  col2  col3
a    10    10    10
b    20    20    20
c    30    30    30

In [225]:
df['col1']

a    10
b    20
c    30
Name: col1, dtype: int32

In [226]:
df['col2'] = df['col2']*2
df['col3'] = df['col3']*3
df

col1  col2  col3
a    10    20    30
b    20    40    60
c    30    60    90

In [227]:
df[['col1', 'col2']]

col1  col2
a    10    20
b    20    40
c    30    60

In [233]:
df.iloc[:2, 0::2] #iloc requires numerical indices for both rows and columns

col1  col3
a    10    30
b    20    60

In [234]:
df = pd.DataFrame(data=np.random.randn(6,5), index='A B C D E F'.split(), columns='X Y Z W V'.split())

In [235]:
df

X         Y         Z         W         V
A  1.290565 -0.474398 -0.424413  1.612874  1.396126
B  1.294915 -3.459852  0.708031 -0.222274 -1.758101
C  0.641826 -0.302739  0.933889 -0.126715 -1.491075
D  0.770603  1.689726  0.046062  1.409138 -0.845154
E -0.671594 -0.274987 -0.667076  1.217811 -0.430092
F -0.771512  0.329411 -1.021229 -0.902730 -0.518940

In [236]:
df.loc[['A','B','D'], ["X", 'Y', 'Z']]

X         Y         Z
A  1.290565 -0.474398 -0.424413
B  1.294915 -3.459852  0.708031
D  0.770603  1.689726  0.046062

In [237]:
df.reset_index(inplace=False) #by default

index         X         Y         Z         W         V
0     A  1.290565 -0.474398 -0.424413  1.612874  1.396126
1     B  1.294915 -3.459852  0.708031 -0.222274 -1.758101
2     C  0.641826 -0.302739  0.933889 -0.126715 -1.491075
3     D  0.770603  1.689726  0.046062  1.409138 -0.845154
4     E -0.671594 -0.274987 -0.667076  1.217811 -0.430092
5     F -0.771512  0.329411 -1.021229 -0.902730 -0.518940

In [240]:
df.set_index('Y', inplace=False) #you lose your index data, inplace=False by default

X         Z         W         V
Y                                                
-0.474398  1.290565 -0.424413  1.612874  1.396126
-3.459852  1.294915  0.708031 -0.222274 -1.758101
-0.302739  0.641826  0.933889 -0.126715 -1.491075
 1.689726  0.770603  0.046062  1.409138 -0.845154
-0.274987 -0.671594 -0.667076  1.217811 -0.430092
 0.329411 -0.771512 -1.021229 -0.902730 -0.518940

In [239]:
df

X         Y         Z         W         V
A  1.290565 -0.474398 -0.424413  1.612874  1.396126
B  1.294915 -3.459852  0.708031 -0.222274 -1.758101
C  0.641826 -0.302739  0.933889 -0.126715 -1.491075
D  0.770603  1.689726  0.046062  1.409138 -0.845154
E -0.671594 -0.274987 -0.667076  1.217811 -0.430092
F -0.771512  0.329411 -1.021229 -0.902730 -0.518940

In [242]:
df.insert(2, 'YY', np.arange(6))

In [243]:
df

X         Y  YY         Z         W         V
A  1.290565 -0.474398   0 -0.424413  1.612874  1.396126
B  1.294915 -3.459852   1  0.708031 -0.222274 -1.758101
C  0.641826 -0.302739   2  0.933889 -0.126715 -1.491075
D  0.770603  1.689726   3  0.046062  1.409138 -0.845154
E -0.671594 -0.274987   4 -0.667076  1.217811 -0.430092
F -0.771512  0.329411   5 -1.021229 -0.902730 -0.518940

In [244]:
df.drop('YY', axis=1, inplace=True)

In [245]:
df

X         Y         Z         W         V
A  1.290565 -0.474398 -0.424413  1.612874  1.396126
B  1.294915 -3.459852  0.708031 -0.222274 -1.758101
C  0.641826 -0.302739  0.933889 -0.126715 -1.491075
D  0.770603  1.689726  0.046062  1.409138 -0.845154
E -0.671594 -0.274987 -0.667076  1.217811 -0.430092
F -0.771512  0.329411 -1.021229 -0.902730 -0.518940